Quiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('user/', include('account.urls')),
    path('quiz/', include('quiztest.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiztest/models.py
from django.db import models
import pandas as pd
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=15)
    
    class Meta:
        verbose_name_plural = "Categories"
    
    def __str__(self): #To return the name instead of "Category object (x)" on Admin page
        return self.name

class Quiz(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    quiz_file = models.FileField(upload_to='quiz/')    
    duration_minutes = models.PositiveIntegerField(default=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name_plural = "Quizzes"
    
    def __str__(self):
        return self.title
    
    # Call the function on quiz save
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.quiz_file:
            self.import_quiz_from_excel()
    
    # Extract excel file        
    def import_quiz_from_excel(self):
        # read excel file
        df = pd.read_excel(self.quiz_file.path)
        # iterate over the each row
        for index, row in df.iterrows():
            # extract question text, choices and correct answer from the row
            question_text = row['Question']
            choice1 = row['A']
            choice2 = row['B']
            choice3 = row['C']
            choice4 = row['D']
            correct_answer = row['Answer']
            is_multiple = False
            if 'is_multiple' in row and (row['is_multiple'] == True or str(row['is_multiple']).lower() in ['1', 'true', 'yes']):
                is_multiple = True
            elif len(correct_answer) > 1:
                is_multiple = True
            
            # create questions object with multiple choice
            question, _ = Question.objects.get_or_create(
                quiz=self, text=question_text,
                defaults={'is_multiple': is_multiple}
            )
            question.is_multiple = is_multiple
            question.save()

            # create choices object with multiple correct answers
            choice_1 = Choice.objects.get_or_create(question=question, text=choice1, is_correct='A' in correct_answer)
            choice_2 = Choice.objects.get_or_create(question=question, text=choice2, is_correct='B' in correct_answer)
            choice_3 = Choice.objects.get_or_create(question=question, text=choice3, is_correct='C' in correct_answer)
            choice_4 = Choice.objects.get_or_create(question=question, text=choice4, is_correct='D' in correct_answer)

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.TextField()
    # Is this question multiple choice?
    is_multiple = models.BooleanField(default=False)
    
    def __str__(self):
        return self.text[:50]
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.question.text[:50]}, {self.text[:20]}"
    
class QuizSubmission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.IntegerField()
    submitted_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user}, {self.quiz.title}"
    
class UserRank(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rank = models.IntegerField(null=True, blank=True)
    total_score = models.IntegerField(null=True, blank=True)
    
    def __str__(self):
        return f"{self.rank}, {self.user.username}"
    
@receiver(post_save, sender=QuizSubmission)
def update_leaderboard(sender, instance, created, **kwargs):
    if created:
        update_leaderboard()

def update_leaderboard():
    # Count the sum of scores for all users
    user_scores = QuizSubmission.objects.values('user').annotate(total_score=Sum('score')).order_by('-total_score')
    
    # Update rank based on the sorted list
    rank = 1
    for entry in user_scores:
        user_id = entry['user']
        total_score = entry['total_score']
        
        user_rank, created = UserRank.objects.get_or_create(user_id=user_id)
        user_rank.rank = rank
        user_rank.total_score = total_score
        user_rank.save()
        
        rank += 1

templates/blogs.html
{% extends 'index.html' %}
{% block title %}Blogs{% endblock title %}

{% block content %}

    <h1 class="display-4 text-center my-5">Blogs</h1>

    <main>
        <div class="container col-md-6 col-sm-12">
            {% for year_count in year_blog_count %}
            <ul class="list mb-4 p-3">
                <h3>{{year_count.year}} - {{year_count.count}} blog(s)</h3>
                {% for blog in blogs %}
                {% if blog.created_at|date:"Y" == year_count.year|stringformat:"s" %}
                <li class="d-flex justify-content-between mb-2">
                    <a href="{% url 'blog' blog.id %}">{{blog.title}}</a>
                    <span title="26 Jul 23 08:05 UTC" class="text-secondary">{{blog.created_at}}</span>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
    </main>

{% endblock content %}

templates/confirm.html
{% extends 'index.html' %}

{% block title %} @{{request.user.username}} Profile Delete Confirmation {% endblock title %}

{% block content %}


<h1 class="display-4 text-center my-5">Confirmation Page</h1>

  <div class="container">
    <form action="" method="POST" class="">
        {% csrf_token %}
        <p class="fs-4"><b>@{{request.user.username}}</b>, Are you sure you want to delete your profile??</p>
        <a href="{% url 'profile' request.user.username %}" class="btn btn-success" type="button">Back to Profile</a>
        <input class="btn btn-danger" type="submit" value="Confirm">
    </form>
  </div>

{% endblock content %}

templates/contact.html
{% extends 'index.html' %}
{% block title %}Contact Us{% endblock title %}

{% block content %}

	<h1 class="display-4 text-center my-5">Contact Us</h1>
	<main>
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6">
					<form action="" method="post" class="contact-form">
						{% csrf_token %}
						<div class="form-group mb-4">
							<label for="username">Username</label>
							<input type="text" id="username" name="username" value="{{request.user.username}}" class="form-control"
								disabled>
						</div>

						<div class="form-group mb-4">
							<label for="subject">Subject</label>
							<input type="text" id="subject" name="subject" required class="form-control">
						</div>

						<div class="form-group mb-4">
							<label for="message">Message</label>
							<textarea id="message" name="message" rows="5" required class="form-control"></textarea>
						</div>

						<button type="submit" class="btn btn-primary btn-block">Send Message</button>
					</form>
				</div>
			</div>
		</div>
	</main>

{% endblock content %}

templates/dashboard.html
{% extends 'index.html' %}
{% block title %}Dashboard{% endblock title %}

{% block content %}
    <h1 class="display-4 text-center my-5">Dashboard</h1>

    <!-- Dashboard Code Goes Here -->
    <div class="container">
        <div class="row">
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center mt-4">
                        <h1 class="card-title pricing-card-title">{{total_users}}</h1>
                        <p class="card-text">Active Users</p>
                        <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">{{today_users}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">{{gain_users|default:0}}%</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center mt-4">
                        <h1 class="card-title pricing-card-title">{{total_quizzes}}</h1>
                        <p class="card-text">Quizzes</p>
                        <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">{{today_quizzes}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">{{gain_quizzes|default:0}}%</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center mt-4">
                        <h1 class="card-title pricing-card-title">{{total_quiz_submit}}</h1>
                        <p class="card-text">Submissions</p>
                        <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">{{today_quiz_submit}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">{{gain_quiz_submit|default:0}}%</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <div class="card">
                    <div class="card-body text-center mt-4">
                        <h1 class="card-title pricing-card-title">{{total_questions}}</h1>
                        <p class="card-text">Questions</p>
                        <ul class="list-group mt-5">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Today
                                <span class="badge bg-primary rounded-pill">{{today_questions}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gain %
                                <span class="badge bg-primary rounded-pill">{{gain_questions|default:0}}%</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12 col-md-12 mb-3">
                <h2 class="mb-3 text-center">Inbox</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Username</th>
                            <th scope="col">Subject</th>
                            <th scope="col">Time</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for message in messages %}
                        <tr class="table-{% if not message.is_read %}active{% endif %}">
                            <th scope="row">{{forloop.counter}}</th>
                            <td><a href="{% url 'profile' message.user.username %}">@{{message.user.username}}</a></td>
                            <td>{{message.subject}}</td>
                            <td>{{message.created_at}}</td>
                            <td><a href="{% url 'message' message.id %}" class="btn btn-sm btn-primary">Open</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %}

templates/downloads.html
{% extends 'index.html' %}
{% block title %}Blogs{% endblock title %}

{% block content %}

    <h1 class="display-4 text-center my-5">Downloads</h1>


    <main>
        <div class="container col-md-8 col-sm-12">
            <div class="download-item mb-4">
                <h2 class="">Research Paper 1</h2>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio facere accusantium rem
                    explicabo eos molestias enim itaque, quis nam.</p>
                <a href="" class="btn btn-primary">Download</a>
                <hr>
            </div>
            <div class="download-item mb-4">
                <h2>Reports</h2>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio facere accusantium rem
                    explicabo eos molestias enim itaque, quis nam.</p>
                <a href="" class="btn btn-primary">Download</a>
                <hr>
            </div>
            <div class="download-item mb-4">
                <h2>Research Paper 1</h2>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio facere accusantium rem
                    explicabo eos molestias enim itaque, quis nam.</p>
                <a href="" class="btn btn-primary">Download</a>
                <hr>
            </div>
        </div>
    </main>

{% endblock content %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Welcome Home {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" integrity="sha512-dPXYcDub/aeb08c63jRq/k6GaKccl256JQy/AnOq7CAnEZ9FzSL9wSbcZkMp4R26vBsMLFYH4kQ67/bbV8XaCQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    
    {% include "components/navbar.html" %}

    {% block content %}

    {% endblock content %}

    {% include "components/footer.html" %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script>
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))        
    </script>
</body>
</html>

templates/leaderboard.html
{% extends 'index.html' %}

{% block title %}Leaderboard{% endblock title %}

{% block content %}

<style>
    .leaderboard-avatar {
        width: 100px !important;
        height: 100px !important;
        object-fit: cover;
        border-radius: 50%;
        display: block;
    }
    .leaderboard-avatar.top1 {
        width: 130px !important;
        height: 130px !important;
    }
    .leaderboard-avatar.othertop {
        width: 40px !important;
        height: 40px !important;
    }
    .bg-bronze {
        background-color: #cd7f32 !important; /* Bronze color */
        color: #fff !important;
    }
    .bg-silver {
        background-color: #bec2cb !important; /* Silver color */
        color: #fff !important;
    }
    .bg-lightblue {
        background-color: #add8e6 !important; /* Lightblue color */
        color: #fff !important;
    }
    .other-user-card {
        max-width: 450px;
        margin-left: auto;
        margin-right: auto;
        min-height: 70px;
    }
    .btn-view-profile {
        border: none !important;
        box-shadow: none !important;
        font-size: 0.80rem;
        padding: 2px 10px;
        line-height: 2.0;
        background-color: #e1e3e0ff !important;
        color: #000 !important;
    }
    .btn-view-profile.top1 {
        background-color: #F8ECD9 !important;
        color: #000 !important;
    }
    .btn-view-profile.top2 {
        background-color: #e1e3e0ff !important;
        color: #000 !important;
    }
    .btn-view-profile.top3 {
        background-color: #f7ede2ff !important;
        color: #000 !important;
    }
    .badge-other-top {
        font-size: 1.2rem;
        padding: 0.4em 1.0em;
    }
</style>

<div class="container text-center">
    <h1 class="display-4 text-center my-5">Leaderboard</h1>

    {% if leaderboard_users|length == 0 %}
        <h4 class="text-center text-danger">No User Available on Leaderboard</h4>
    {% else %}
        <div class="row justify-content-center align-items-end my-5">
            {% with top_users=leaderboard_users|slice:":3" %}
                {% if top_users|length == 3 %}
                    <!-- TOP2 -->
                    <div class="col-4 d-flex flex-column align-items-center">
                        <span class="badge bg-silver mb-2">TOP 2</span>
                        <img src="{{top_users.1.user.profile.profile_img.url}}" class="leaderboard-avatar" alt="user-profile">
                        <h5>@{{top_users.1.user.username}}</h5>
                        <span class="fw-bold text-success">{{top_users.1.total_score}} points</span>
                        <a href="{% url 'profile' top_users.1.user.username %}" class="btn btn-outline-primary btn-sm btn-view-profile top2 mt-2">View Profile</a>
                    </div>
                    <!-- TOP1 -->
                    <div class="col-4 d-flex flex-column align-items-center">
                        <span class="badge bg-warning text-dark mb-2">TOP 1</span>
                        <img src="{{top_users.0.user.profile.profile_img.url}}" class="leaderboard-avatar top1" alt="user-profile">
                        <h4 class="fw-bold">@{{top_users.0.user.username}}</h4>
                        <span class="fw-bold text-success">{{top_users.0.total_score}} points</span>
                        <a href="{% url 'profile' top_users.0.user.username %}" class="btn btn-outline-primary btn-sm btn-view-profile top1 mt-2">View Profile</a>
                    </div>
                    <!-- TOP3 -->
                    <div class="col-4 d-flex flex-column align-items-center">
                        <span class="badge bg-bronze mb-2">TOP 3</span>
                        <img src="{{top_users.2.user.profile.profile_img.url}}" class="leaderboard-avatar" alt="user-profile">
                        <h5>@{{top_users.2.user.username}}</h5>
                        <span class="fw-bold text-success">{{top_users.2.total_score}} points</span>
                        <a href="{% url 'profile' top_users.2.user.username %}" class="btn btn-outline-primary btn-sm btn-view-profile top3 mt-2">View Profile</a>
                    </div>
                {% else %}
                    {% for user in top_users %}
                        <div class="col d-flex flex-column align-items-center">
                            <span class="badge bg-silver mb-2">TOP {{forloop.counter}}</span>
                            <img src="{{user.user.profile.profile_img.url}}" class="leaderboard-avatar" alt="user-profile">
                            <h5>@{{user.user.username}}</h5>
                            <span class="fw-bold text-success">{{user.total_score}} points</span>
                            <a href="{% url 'profile' user.user.username %}" class="btn btn-outline-primary btn-sm btn-view-profile mt-2">View Profile</a>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>

        <!-- Other users -->
        <div class="row my-3 justify-content-center">
            <div class="col-12 col-md-8">
                {% for rank in leaderboard_users|slice:"3:" %}
                    <div class="card other-user-card p-2 d-flex flex-row align-items-center mb-2">
                        <span class="badge bg-lightblue badge-other-top me-2">{{forloop.counter|add:3}}</span>
                        <img src="{{rank.user.profile.profile_img.url}}" class="leaderboard-avatar othertop ms-2 me-2" alt="user-profile">
                        <div class="flex-grow-1 d-flex justify-content-between align-items-center">
                            <a href="{% url 'profile' rank.user.username %}" class="ms-2">@{{rank.user.username}}</a>
                            <span class="fw-bold text-success">{{rank.total_score}} points</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
</div>
    
{% endblock content %}

templates/login.html
{% extends "index.html" %}

{% block title %} Login {% endblock title %}

{% block content %}
    <h1 class="display-4 text-center my-5">Login</h1>

    <div class="container">
        <div class="row row-cols-sm-1 row-cols-lg-3 container">
            <div class="col-12">
            </div>
            <div class="col-12">
                <div>
                    {% for message in messages %}
                    <h5 class="text-danger">{{message}}</h5>
                    {% endfor %}
                </div>
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label visually-hidden">Username</label>
                        <input type="username" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Username">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label visually-hidden">Password</label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required>
                    </div>
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Remember me</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
                <p class="my-2">Not a user? <a href="{% url 'register' %}">Register</a></p>
            </div>
            <div class="col-12">
            </div>
        </div>
    </div>

{% endblock content %}

templates/quiz.html
{% extends 'index.html' %}

{% block title %} {{quiz.title}} {% endblock title %}

{% block content %}

    <style>
        .questions {
            user-select: none;
        }
    </style>
    
    <h1 class="display-4 text-center my-5">{{quiz.title}} - ({{quiz.question_set.all|length}})</h1>
    <p class="fs-5 text-center container">{{quiz.description}}</p>

    <div class="container">
        <div class="d-flex justify-content-between">
            <span class="fs-5">{{quiz.created_at}}</span>
            <span class="fs-5" id="timer">{{ quiz.duration_minutes|default:10|stringformat:"02d" }}:00</span>
        </div>

        {% for message in messages %}
        <div id="message-div">
            <h4 class="text-center text-success">{{message}}</h4>
        </div>
        {% endfor %}

        <div class="questions my-4">
            {% for question in quiz.question_set.all %}
            <div class="card mb-2 question">
                <div class="card-header fw-bold">
                    Question {{forloop.counter}}
                </div>

                <div class="card-body">
                    <p class="card-text">{{question.text}}</p>

                    {% for option in question.choice_set.all %}
                    <div class="form-check">
                        <label class="form-check-label" for="{{option.id}}">
                            <input class="form-check-input"
                                value="{{option.text}}"
                                type="{% if question.is_multiple %}checkbox{% else %}radio{% endif %}"
                                name="{{option.question.id}}{% if question.is_multiple %}[]{% endif %}"
                                id="{{option.id}}">
                            {{option.text}}
                        </label>
                        {% if option.is_correct %}
                        <span class="visually-hidden correct-answer">{{option.text}}</span>
                        {% endif %}
                    </div>
                    {% endfor %}

                </div>
            </div>
            {% endfor %}
        </div>

        <form action="" method="post" id="quiz-form">
            {% csrf_token %}
            <input type="hidden" name="score" value='0' id="user-score">
            <button type="submit" class="btn btn-primary" id="submit-button">Submit the quiz</button>
        </form>
    </div>

<script>
    // Elements
    var submitButton = document.getElementById("submit-button");
    var timerSpan = document.getElementById("timer");
    var quizForm = document.getElementById("quiz-form")
    var questions = document.querySelectorAll(".question");
    var userScoreInput = document.getElementById("user-score");

    var quizDuration = {{ quiz.duration_minutes|default:10 }} * 60;

    // Update Timer
    function updateTimer() {
        var minutes = Math.floor(quizDuration / 60);
        var seconds = quizDuration % 60;

        var formattedMinutes = minutes.toString().padStart(2, '0');
        var formattedSeconds = seconds.toString().padStart(2, '0');

        timerSpan.innerText = formattedMinutes + ":" + formattedSeconds;

        if (quizDuration <= 0) {
            //Automaticall submit the quiz
            clearTimeout(quizTimerId);
            submitQuiz();
        } else if (document.getElementById("message-div")) {
            clearTimeout(quizTimerId);
            highlightCorretAnswer();
        } else {
            // decrement the timer value by 1s
            quizDuration--;
        }
    }

    function submitQuiz() {
        // Calculate the score
        calculateScore();

        //submit the quiz
        quizForm.submit();
    }

    // Check right answer and cal the score
    function calculateScore() {
        var score = 0;

        // Loop through question
        questions.forEach(question => {
            var selectedInput = question.querySelector('input:checked');
            var correctAnswer = question.querySelector(".correct-answer").innerText;

            // Check if the aswer is correct or not
            if (selectedInput && selectedInput.value == correctAnswer) {
                score += 1;
            }
        });

        // Update the hidden input field with score in form
        userScoreInput.value = score;
    }

    // Highlight the correct answer while showing the result
    function highlightCorretAnswer() {
        questions.forEach(question => {
            var correctAnswer = question.querySelector(".correct-answer");
            correctAnswer.previousElementSibling.querySelector("input").classList.add("bg-success");
            correctAnswer.previousElementSibling.classList.add("fw-bold");
        })

        // disable submit button
        submitButton.disabled = true;

        // disable all questions
        var options = document.querySelectorAll(".form-check-input");
        options.forEach(option => {
            option.disabled = true;
        });
    }

    // Attach event listener to submit button
    submitButton.addEventListener("click", submitQuiz);

    // Timer interval
    quizTimerId = setInterval(updateTimer, 1000);
</script>

{% endblock content %}

templates/search-users.html
{% extends 'index.html' %}

{% block title %}User Search{% endblock title %}

{% block content %}

<div class="container text-center">
    <h1 class="display-4 text-center">Search result for query - {{query}}</h1>

    <div class="row my-5 row-cols-sm-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 mx-3">
        {% if users|length == 0 %}
        <div class="col-lg-4 position-relative mb-4">
            <h4 class="text-center text-danger">No User related to this query!</h4>
        </div>
        {% else %}
        {% for user in users %}
        <div class="col-lg-4 position-relative mb-4">
            <img src="{{user.profile.profile_img.url}}" class="img-fluid" width="150" height="150" alt="user-profile">
            <h2 class="fw-normal">@{{user.username}}</h2>
            <p>{{user.profile.bio|truncatewords:5}}</p>
            <p><a class="btn btn-secondary" href="{% url 'profile' user.username %}">View Profile</a></p>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>
    
{% endblock content %}